name: Sync develop to main

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Force push main to develop
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout develop
          git reset --hard origin/main
          git push origin develop --force
